// Code generated by ogen, DO NOT EDIT.

package server

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateUserOperation        OperationName = "CreateUser"
	GetUserByUsernameOperation OperationName = "GetUserByUsername"
)
