// Code generated by ogen, DO NOT EDIT.

package server

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateUser implements createUser operation.
//
// Create a new user.
//
// POST /users
func (UnimplementedHandler) CreateUser(ctx context.Context, req *CreateUserRequest) (r CreateUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserByUsername implements getUserByUsername operation.
//
// Get a user by username.
//
// GET /users/{username}
func (UnimplementedHandler) GetUserByUsername(ctx context.Context, params GetUserByUsernameParams) (r GetUserByUsernameRes, _ error) {
	return r, ht.ErrNotImplemented
}
