-- generated by migrate create -ext sql -dir deployments/db/migrations -seq create_users

CREATE TABLE users (
	id BIGSERIAL PRIMARY KEY,
	username VARCHAR(255) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UNIQUE(username)
);

CREATE INDEX name_idx ON users (username);